#!/usr/bin/env node
/**
 * render-manual.mjs — manifests → MANUAL.md
 *
 * Place in tools/manual-generator/. Run after a capture pass, from the repo root:
 *   MANUAL_LOCALE=es_ES node tools/manual-generator/render-manual.mjs
 *
 * MANUAL.md is a build artifact and is overwritten. Hand-written prose lives in
 * _intro.md and _outro.md, which this script only ever reads.
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const LOCALE = process.env.MANUAL_LOCALE ?? 'en_GB';
const ROOT = process.env.MANUAL_ROOT ?? path.join('docs', 'manual');
const OUT = process.env.MANUAL_OUT ?? path.join(ROOT, LOCALE);

const STRINGS = {
  en_GB: { toc: 'Contents', note: 'Note', banner: (p, g, d) =>
    `Generated for **${p}** on GLPI ${g} — ${d}. Screenshots are produced automatically; do not edit this file by hand.` },
  es_ES: { toc: 'Índice', note: 'Nota', banner: (p, g, d) =>
    `Generado para **${p}** en GLPI ${g} — ${d}. Las capturas se generan automáticamente; no edite este archivo a mano.` },
  fr_FR: { toc: 'Sommaire', note: 'Note', banner: (p, g, d) =>
    `Généré pour **${p}** sur GLPI ${g} — ${d}. Les captures sont générées automatiquement ; ne modifiez pas ce fichier à la main.` },
};
const S = STRINGS[LOCALE] ?? STRINGS.en_GB;

const slugify = (s) => s.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-|-$/g, '');

async function readIfPresent(p) {
  try { return (await fs.readFile(p, 'utf8')).trim(); } catch { return ''; }
}

/** Plugin name and version from setup.php; env wins if provided. */
async function pluginInfo() {
  let name = process.env.PLUGIN_NAME ?? path.basename(process.cwd());
  let version = process.env.PLUGIN_VERSION ?? '';
  if (!version) {
    const setup = await readIfPresent('setup.php');
    version = setup.match(/define\(\s*'PLUGIN_\w+_VERSION'\s*,\s*'([^']+)'/)?.[1] ?? 'unknown';
    const declared = setup.match(/PLUGIN_(\w+)_VERSION/)?.[1];
    if (declared && !process.env.PLUGIN_NAME) name = declared.toLowerCase();
  }
  return { name, version, glpi: process.env.GLPI_VERSION ?? '11.0' };
}

async function loadManifests() {
  const dir = path.join(OUT, '.manifests');
  let files;
  try {
    files = (await fs.readdir(dir)).filter((f) => f.endsWith('.json'));
  } catch {
    throw new Error(`no manifests in ${dir} — run the capture pass first`);
  }
  if (files.length === 0) throw new Error(`no manifests in ${dir} — run the capture pass first`);
  const all = await Promise.all(
    files.map(async (f) => JSON.parse(await fs.readFile(path.join(dir, f), 'utf8'))),
  );
  return all.sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
}

/** Chapter asset folders are prefixed with the zero-padded chapter number so they sort like the manual, even past 9 chapters. */
function assetDirName(chapterNum, slug) {
  return `${String(chapterNum).padStart(2, '0')}-${slug}`;
}

/**
 * Rename each manifest's assets/<slug> folder to assets/<N>-<slug>, N being its 1-based
 * chapter position. Idempotent: a folder already carrying its current prefix is left alone,
 * and a stale prefix (from a manual reorder) is renamed to the new one.
 */
async function renumberAssetDirs(manifests) {
  const assetsRoot = path.join(OUT, 'assets');
  for (const [i, m] of manifests.entries()) {
    const wanted = assetDirName(i + 1, m.slug);
    const wantedAbs = path.join(assetsRoot, wanted);
    const alreadyRenamed = await fs.stat(wantedAbs).then(() => true, () => false);
    if (alreadyRenamed) continue;
    let entries;
    try {
      entries = await fs.readdir(assetsRoot);
    } catch {
      continue;
    }
    const stale = entries.find((e) => e === m.slug || e.endsWith(`-${m.slug}`));
    if (stale && stale !== wanted) {
      await fs.rename(path.join(assetsRoot, stale), wantedAbs);
    }
  }
}

function renderChapter(m, chapterNum) {
  const dir = assetDirName(chapterNum, m.slug);
  const out = [`## ${chapterNum}. ${m.title}`, ''];
  if (m.intro) out.push(m.intro, '');
  for (const step of m.steps) {
    out.push(`### ${chapterNum}.${step.seq} ${step.title}`, '');
    if (step.body) out.push(step.body, '');
    for (const shot of step.shots) {
      const alt = (shot.caption ?? `${m.title} — ${step.title}`).replace(/[[\]]/g, '');
      out.push(`![${alt}](assets/${dir}/${shot.file})`, '');
      if (shot.caption) out.push(`*${shot.caption}*`, '');
    }
    for (const note of step.notes) out.push(`> **${S.note}:** ${note}`, '');
  }
  return out.join('\n');
}

const main = async () => {
  const { name, version, glpi } = await pluginInfo();
  const manifests = await loadManifests();
  await renumberAssetDirs(manifests);
  const date = new Date().toISOString().slice(0, 10);

  const toc = manifests
    .map((m, i) => `${i + 1}. [${m.title}](#${slugify(`${i + 1}. ${m.title}`)})`)
    .join('\n');

  const doc = [
    `# ${name} — User Manual`,
    '',
    `<!-- GENERATED FILE — edit the specs in tools/manual-generator/specs/ or _intro.md / _outro.md -->`,
    `> ${S.banner(`${name} ${version}`, glpi, date)}`,
    '',
    await readIfPresent(path.join(OUT, '_intro.md')),
    '',
    `## ${S.toc}`,
    '',
    toc,
    '',
    ...manifests.map((m, i) => renderChapter(m, i + 1)),
    await readIfPresent(path.join(OUT, '_outro.md')),
    '',
  ]
    .filter((block, i, arr) => !(block === '' && arr[i - 1] === '')) // collapse blank runs
    .join('\n');

  const target = path.join(OUT, 'MANUAL.md');
  await fs.writeFile(target, doc.replace(/\n{3,}/g, '\n\n'), 'utf8');

  const shots = manifests.reduce((n, m) => n + m.steps.reduce((k, s) => k + s.shots.length, 0), 0);
  console.log(`${target}: ${manifests.length} chapters, ${shots} screenshots, ${LOCALE}`);
};

main().catch((err) => {
  console.error(String(err.message ?? err));
  process.exit(1);
});
